### ISSUE TITLE
Migrate to a better data format Instead of JSON

### ISSUE THREAD

**Issue by Ice3man543** [ReconJSON/ReconJSON#1]
The current JSON format you are using has it's own limitation the biggest of them being really hard to edit it. In order to make changes inside a json object, or add new host objects, you'd have to load the whole structure into the memory and then make a simple change. 

A better format would be [JsonLines](http://jsonlines.org/). To be honest, i've not really liked it but it's a definite improvement over the old structure. So, instead of having a big json array, you can have multiple new-line separated json objects in a file.

```
{"subdomain":"example.acme.com", "ipv4":"192.168.0.1"}
{"subdomain":"example2.acme.com", "ipv4":"192.168.0.2"}
```
This could also allow us to store each host's details in separate files making them greppable really easily. 

Or maybe, you can use another approach where there is a hosts.json file containing a big json array listing all hosts present. Like - 
```
cat hosts.json 
[
    {"host":"example.acme.com"}
]
```
And then for each host or IP Address present inside that hosts.json file, there can be a json file. 

If anyone has ideas for any better file format specifications, i'd love to hear them. 

When we were working on a project (abandoned now), we worked on a graph based format. Each detail was a node. So, the host was the root node. And it contained different nodes recursively inside it describing the node before it. I have the code example implemented, it used gob to serialize the object and then base64 encode it and then gzip compress it to save space. Play around with it [here](https://gist.github.com/Ice3man543/e462bec952947910ac2e71dad4956f37). Maybe we can use that one since it's more compact in my opinion.

Thank you.

**Comment by 0xdevalias** [comment]
While I personally love the idea of graphs for this sort of thing, I wonder if it's not going 'too far' into the abstract for this sort of thing.

Ideally, as I see it, the standard should be the simplest, least effort way for a tool maintainer to output things in a standard format, ideally using features common to the language.

I'd have to think a bit more before I comment on the 'large json nest' aspect, but the way I see this, it should be an output format, rather than a 'working copy'.

If people then want to create tooling to transform this standard 'intermediary' into whatever else, then that's cool.

**Comment by Rhynorater** [comment]
Great suggestions, @Ice3man543! I think JSONLines is certainly something we should implement. This fixes our grep-ability issues AND it is super easy to convert JSONlines into readable JSON objects using ```python -m json.tool``` or by the use of [jq](https://github.com/stedolan/jq). Such a good idea :) I'll integrate this into the standard later today (EST) if there aren't any further objections. 

However, I agree with @0xdevalias about breaking the hosts into different files. While this would be nice to not have to load the whole structure into memory to remove one host, I think the output from the tools should be in one file, in a consistent JSON format to cater to all the different programming languages. I don't think the idea of Recon.JSON is longterm storage - it's more of a universal output format. As a result, loading up all this data into memory shouldn't be too big of an issue.

**Comment by Ice3man543** [comment]
@Rhynorater I agree for json lines option. It's a good format. :+1:

**Comment by codingo** [comment]
I agree on everything, just one point:

```
While I personally love the idea of graphs for this sort of thing, I wonder if it's not going 'too far' into the abstract for this sort of thing.
```

I believe one of the large drivers for such a standard will be to encourage new integrations and innovation in our space. We should each focus on doing one thing, and doing it as well as we can - the unix way, whilst opening the door for other products to come in.

Graphing and visualizations should be encouraged in additional tools, and even if this isn't the solution to encouraging that, we should strive to make ReconJSON a practice which will enable all manner of new integrations.

In this case I agree with not using folders, but I did feel it was important to raise this point, and although I do believe @0xdevalias feels the same way, I wanted to highlight what I believe should be a core tenant of creating such a standard.

**Comment by deadbits** [comment]
I'm not super familiar with JSONLines, but I'd assume that if this ReconJSON schema is adopted widely many people will want to integrate into their tools and applications - Is JSONLines something that's commonly supported by web frameworks, Python libraries, databases like say MongoDB (minus db import/export), and so on?

Right now it seems that essentially everyone developing tools in this space are using pure JSON schemas - meaning to get traction they'd need to adapt their applications to fit JSONLines instead of using something that already works with what they are using.

I could be way off base here, as again I'm not familiar with JSON Lines or how well it interacts with common libraries, languages, db's, etc., but just a few questions I had when reading this ticket.

**Comment by deadbits** [comment]
Also just another thought, you can easily grep normal JSON using JQ anyways so I'm not sure I see the benefit of JSON Lines being more easily greppable - or if it is in fact any more easy to grep than normal JSON if you're using JQ in both cases.

**Comment by Rhynorater** [comment]
@deadbits - good points. I just noticed that JSONLines is not a valid json structure when loaded from a file. I'd be more inclined to make something similar to JSONLines, but that also contains a valid JSON structure. Something like this:
```
[
{"type":"Host"...},
{"type":"Host"...},
{"type":"Host"...}
]
```
Where hosts are still defined on each line, but are also valid JSON structures. This maintains the normal grep-ability, but also keeps the form minimalistic. Thoughts @deadbits @codingo @Ice3man543 @michenriksen @0xdevalias ?

**Comment by Rhynorater** [comment]
This allows for #7 to validate more easily as well.

**Comment by Rhynorater** [comment]
@Ice3man543 Please read the section I just published. Feel free to add comments here before making changes or just merge them in yourself if you feel the changes are objectively better.

**Comment by Rhynorater** [comment]
@Ice3man543 As an update, I have partially migrated the README.md. However, its getting late so I'm headed to bed. Will try to finish tomorrow AM (GMT +5)

**Comment by caffix** [comment]
@codingo I agree with your point regarding the importance of attempting to consider innovation during the development of this standard.

Recon and OSINT information gathering have been showing the value of using link graphs to manage collected data for years. This makes perfect sense as well, due to the fact that we are attempting to represent/model networks. As you pointed out, this also helps when trying to visualize the networks.

Amass currently leverages link graphs, internally, to manage the data collected during enumerations. I have experienced the advantages of using this representation, such as avoiding redundant data and making it easier to deal with the many-to-many relationships that exist within the networks we are investigating.

I would definitely encourage this group to consider outputting this data so that different types of elements are saved separately and their relationships exposed in order to link them together.

**Comment by codingo** [comment]
Most definitely. Since I wrote that @michenriksen raised #6 which makes this cleaner for outside tooling. When designing a graph or a dashboard you could monitor this change log to know when updates to the base object have been made.

**Comment by Rhynorater** [comment]
I really feel like making this a graph structure is going to take away from the simplicity of the format, @caffix and @codingo. Perhaps some goal and scope definition for this project is in order. I will try to get something out around that later on today.

**Comment by deadbits** [comment]
@Rhynorater Agreed^ If users want to use the schema to make graphs within their tools, that's not super hard to do with JSON. Lots of tools do it already

**Comment by Rhynorater** [comment]
@Ice3man543 are you satisfied with the current format?

**Comment by Ice3man543** [comment]
Yeah, I am.
